name: ci-kind

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up KinD
        uses: helm/kind-action@v1.9.0
        with:
          cluster_name: ci
          version: v1.29.0

      - name: Build Docker images
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t game-service:$TAG game-service
          docker build -t order-service:$TAG order-service
          docker build -t analytics-service:$TAG analytics-service
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Load images into KinD
        run: |
          kind load docker-image game-service:$TAG --name ci
          kind load docker-image order-service:$TAG --name ci
          kind load docker-image analytics-service:$TAG --name ci

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/
          kubectl set image deploy/game-deployment game=game-service:$TAG
          kubectl set image deploy/order-deployment order=order-service:$TAG
          kubectl set image deploy/analytics-deployment analytics=analytics-service:$TAG

      - name: Wait for rollouts
        run: |
          kubectl rollout status deploy/game-deployment --timeout=180s
          kubectl rollout status deploy/order-deployment --timeout=180s
          kubectl rollout status deploy/analytics-deployment --timeout=180s

      - name: Run integration tests
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest
          nohup kubectl port-forward svc/game-svc 8081:80 >/tmp/pf-game.log 2>&1 &
          nohup kubectl port-forward svc/order-svc 8082:80 >/tmp/pf-order.log 2>&1 &
          nohup kubectl port-forward svc/analytics-svc 8083:80 >/tmp/pf-analytics.log 2>&1 &
          sleep 6
          sudo apt-get update && sudo apt-get install -y netcat-openbsd
          for p in 8081 8082 8083; do
            for i in {1..40}; do
              nc -z localhost $p && break || sleep 1
            done
          done
          GAME_URL=http://localhost:8081 \
          ORDERS_URL=http://localhost:8082 \
          ANALYTICS_URL=http://localhost:8083 \
          pytest -q tests/test_end_to_end.py
