name: CI/CD (build  rolling deploy  tests)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: game-service
            path: game-service
          - name: order-service
            path: order-service
          - name: analytics-service
            path: analytics-service
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Short tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          docker build -t $REGISTRY/${{ matrix.name }}:${{ steps.vars.outputs.TAG }} \
                       -t $REGISTRY/${{ matrix.name }}:latest \
                       ./${{ matrix.path }}
      - name: Push
        run: |
          docker push $REGISTRY/${{ matrix.name }}:${{ steps.vars.outputs.TAG }}
          docker push $REGISTRY/${{ matrix.name }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
      - name: Configure kubeconfig (base64)
        if: ${{ secrets.KUBE_CONFIG != '' }}
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Substitute registry and apply manifests
        run: |
          find k8s -type f -name "*.yaml" -print0 | xargs -0 sed -i "s#REGISTRY_PLACEHOLDER#${{ secrets.REGISTRY }}#g"
          kubectl apply -f k8s/
      - name: Roll out with unique TAG
        run: |
          TAG=${GITHUB_SHA::7}
          kubectl set image deploy/game-deployment game=${{ secrets.REGISTRY }}/game-service:${TAG}
          kubectl set image deploy/order-deployment order=${{ secrets.REGISTRY }}/order-service:${TAG}
          kubectl set image deploy/analytics-deployment analytics=${{ secrets.REGISTRY }}/analytics-service:${TAG}
      - name: Wait for rollouts
        run: |
          bash scripts/wait_for_rollout.sh game-deployment
          bash scripts/wait_for_rollout.sh order-deployment
          bash scripts/wait_for_rollout.sh analytics-deployment

  post-deploy-tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest
      - name: Run integration tests
        env:
          BASE_URL: ${{ secrets.PROD_BASE_URL }}
        run: pytest -q tests/test_end_to_end.py
