name: Scheduled smoke tests (KinD)

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1.9.0
        with:
          cluster_name: smoke
          version: v1.29.0
      - name: Build + load images
        run: |
          TAG=smoke
          docker build -t game-service:$TAG game-service
          docker build -t order-service:$TAG order-service
          docker build -t analytics-service:$TAG analytics-service
          kind load docker-image game-service:$TAG --name smoke
          kind load docker-image order-service:$TAG --name smoke
          kind load docker-image analytics-service:$TAG --name smoke
      - name: Deploy
        run: |
          kubectl apply -f k8s/
          kubectl set image deploy/game-deployment game=game-service:smoke
          kubectl set image deploy/order-deployment order=order-service:smoke
          kubectl set image deploy/analytics-deployment analytics=analytics-service:smoke
          kubectl rollout status deploy/game-deployment --timeout=180s
          kubectl rollout status deploy/order-deployment --timeout=180s
          kubectl rollout status deploy/analytics-deployment --timeout=180s
      - name: Run tests
        run: |
          python -m pip install --upgrade pip >/dev/null
          pip install requests pytest >/dev/null
          nohup kubectl port-forward svc/game-svc 8081:80 >/tmp/pf-game.log 2>&1 &
          nohup kubectl port-forward svc/order-svc 8082:80 >/tmp/pf-order.log 2>&1 &
          nohup kubectl port-forward svc/analytics-svc 8083:80 >/tmp/pf-analytics.log 2>&1 &
          sleep 6
          GAME_URL=http://localhost:8081 \
          ORDERS_URL=http://localhost:8082 \
          ANALYTICS_URL=http://localhost:8083 \
          pytest -q tests/test_end_to_end.py
